version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/data/postgres
    networks:
      - postgres-compose-network
  app:
    build: .
    container_name: rentalx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - database_ignite
    networks:
      - postgres-compose-network
volumes:
  pgdata:
    driver: local

networks:
  postgres-compose-network:
    driver: bridge